import esbuild from "esbuild";
import process from "process";
import {copyFile, mkdir, rm} from "node:fs/promises";
import {join} from "node:path";
import {builtinModules} from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const releaseDir = "release/hermesian";
const staticAssets = ["manifest.json", "styles.css"];

if (prod) {
	await rm(releaseDir, {recursive: true, force: true});
}

await mkdir(releaseDir, {recursive: true});
await Promise.all(staticAssets.map((asset) => copyFile(asset, join(releaseDir, asset))));

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: join(releaseDir, "main.js"),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
